eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
microservice:    
  payment-services:
     endpoints:
        endpoint:
           uri: http://PAYMENT-SERVICES/payment-provider/paynow/
